services:
  redis:
    profiles: ["development"]
    image: "redis:8-alpine"
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - "redis_data:/data"
    env_file:
      - .env

volumes:
  redis_data:
